server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: review_user:review_pass@tcp(127.0.0.1:3307)/review_db?parseTime=True&loc=Local&charset=utf8mb4
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: reviews
  elasticsearch:
    addresses:
      - http://127.0.0.1:9200
    username: ""
    password: ""
    index: reviews
